trigger: none
pool: agent1_pool

steps: 
- task: PowerShell@2
  displayName: "npm install"
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      npm install

- task: PowerShell@2
  displayName: "npm run build"
  inputs:
    targetType: 'inline'
    script: 'npm run build'
    
- task: PowerShell@2
  displayName: "Download Sonar scaner"
  inputs:
    targetType: 'inline'
    script: |
      Invoke-WebRequest `
              -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip" `
              -OutFile "sonar.zip"
      
            Expand-Archive sonar.zip -DestinationPath "$(Build.SourcesDirectory)\scanner" -Force
      
            $scannerPath = "$(Build.SourcesDirectory)\scanner\sonar-scanner-5.0.1.3006-windows\bin"
            Write-Host "Scanner path: $scannerPath"
      
            # Add to PATH for this pipeline session
            $env:PATH = "$scannerPath;" + $env:PATH
      
            sonar-scanner --version
    
- task: PowerShell@2
  displayName: "run sonar scanner"
  inputs:
    targetType: 'inline'
    script: |
      $env:SONAR_HOST_URL = "http://localhost:9000"
            $env:SONAR_LOGIN = "squ_1854a75e32f76c50b8889dab9ce1f3eb37c947a4"   # Add SONAR_TOKEN in pipeline variables as secret
            sonar-scanner `
              -Dsonar.projectKey=reactapp `
              -Dsonar.sources=. `
              -Dsonar.exclusions=**/node_modules/**,**/build/** `
              -Dsonar.host.url=$env:SONAR_HOST_URL `
              -Dsonar.login=$env:SONAR_LOGIN

- task: ArchiveFiles@2
  displayName: "ArchiveFiles"
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/build.zip'
    replaceExistingArchive: true

- task: AzureCLI@2
  displayName: "push in storage account"
  inputs:
    azureSubscription: 'conn_new'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Current directory:"
      pwd
      
      echo "Files in working directory:"
      ls
      az storage blob upload  --account-name vinodstoragemaina --container-name container22  --name build.zip   --file build.zip  --overwrite true

- task: PublishBuildArtifacts@1
  displayName: "PublishBuildArtifacts"
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/build.zip'
    ArtifactName: 'reactjs'
    publishLocation: 'Container'